services:
  postgres:
    image: postgres:17

    container_name: task-db

    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: task-api

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env

volumes:
  postgres_data: